server:
  port: 2223
  servlet:
    context-path: /api/cars

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        linger_ms: 1
        enable_idempotence: true

car-sharing-app:
  topic-name:
    car-request: car_request_topic