server:
  port: 2223
  servlet:
    context-path: /api/cars

car-sharing-app:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    topic-name: car_request_topic
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    acks: all
    retries: 3
    linger_ms: 1
    enable_idempotence: true